name: Update CHANGES.md with PR Title on Merge

on:
  pull_request:
    types: [closed]
    branches: [develop]

jobs:
  update-changes-md:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Fetch enough history to amend the latest commit

      - name: Read version from version.properties
        id: read_version
        run: |
          # Extract version.name from version.properties in the root folder
          VERSION_NAME=$(grep 'version.name' version.properties | cut -d'=' -f2 | xargs)
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      - name: Update CHANGES.md with PR title if not already present
        run: |
          # Capture the PR title and version name
          PR_TITLE="${{ github.event.pull_request.title }}"
          VERSION_NAME="${{ env.VERSION_NAME }}"

          # Prepare the entry for the changelog
          NEW_ENTRY="- ${PR_TITLE}"

          # Check if PR title already exists anywhere in CHANGES.md
          if grep -qF "${PR_TITLE}" app/CHANGES.md; then
            echo "PR title already exists in CHANGES.md. Skipping update."
            exit 0
          fi

          # Check if the version header already exists in CHANGES.md
          if grep -q "## ${VERSION_NAME}" app/CHANGES.md; then
            # If version header exists, add PR title under it
            sed -i "/## ${VERSION_NAME}/a ${NEW_ENTRY}" app/CHANGES.md
          else
            # If version header doesn't exist, create it with PR title at the top of the file
            echo -e "## ${VERSION_NAME}\n${NEW_ENTRY}\n\n$(cat app/CHANGES.md)" > app/CHANGES.md
          fi

          # Configure Git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Stage and amend the latest commit
          git add app/CHANGES.md
          git commit --amend --no-edit
          
          # Force-push the amended commit to develop
          git push origin HEAD:develop --force
