name: Update File with PR Title on Merge

on:
  pull_request:
    types: [closed]
    branches: [develop]

jobs:
  amend-last-commit-with-pr-title:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add PR title to file and amend latest commit
        run: |
          # Capture the PR title
          PR_TITLE="${{ github.event.pull_request.title }}"
          
          # Add PR title to the file
          echo "${PR_TITLE}" >> your_file.txt
          
          # Configure Git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Stage changes and amend the latest commit
          git add your_file.txt
          git commit --amend --no-edit
          
          # Force-push the amended commit to develop
          git push origin develop --force
