name: Update File with PR Title on Merge

on:
  pull_request:
    types: [closed]
    branches: [develop]

jobs:
  update-file-with-pr-title-on-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        

      - name: Update file with PR title
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "${PR_TITLE}" >> your_file.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add your_file.txt
          git commit -m "Add PR title: ${PR_TITLE} after merge"
          git push origin develop
